import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { destinations, buildFlights, buildHotels, buildCars } from './data/destinations.js';
import { amadeus, getCached, setCache, mapOffer, fetchLiveHotels } from './amadeusClient.js';
import { fetchLiveFlights, fetchLiveHotelsTP } from './travelpayoutsClient.js';
import { fetchDuffelFlights } from './duffelClient.js';
import { fetchLiveHotelsRapidAPI } from './hotelApiClient.js';
import { getCityCulture } from './gemmaClient.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = process.env.PORT || 4000;
const JWT_SECRET = process.env.JWT_SECRET || 'geoflow-dev-secret';

app.use(cors());
app.use(express.json());

// ── Static airport dataset (generated by scripts/fetch-airports.js) ───────────
let airports = [];
try {
  airports = JSON.parse(fs.readFileSync(path.join(__dirname, 'data/airports.json'), 'utf8'));
  console.log(`Loaded ${airports.length} airports`);
} catch {
  console.warn('airports.json missing — run: node scripts/fetch-airports.js');
}

// ── In-memory user store (stand-in for a real DB) ─────────────────────────────
const users = new Map();
const savedByUser = new Map();
const tripsByUser = new Map();

const demoId = 'u-demo';
users.set('explorer@geoflow.com', {
  id: demoId, name: 'Sıla Kırılmaz', email: 'explorer@geoflow.com',
  password: 'explorer', homeAirport: 'Istanbul — IST', currency: 'USD ($)', language: 'English'
});
savedByUser.set(demoId, new Set(['JP', 'FR', 'GR']));
tripsByUser.set(demoId, []);

function publicUser(u) { const { password, ...rest } = u; return rest; }

function auth(req, res, next) {
  const token = (req.headers.authorization || '').replace('Bearer ', '');
  if (!token) return res.status(401).json({ error: 'Missing token' });
  try { req.userId = jwt.verify(token, JWT_SECRET).sub; next(); }
  catch { res.status(401).json({ error: 'Invalid token' }); }
}

// ── REST Countries cache ───────────────────────────────────────────────────────

const ACCENT_COLORS = [
  '#2D4677', '#9B2C2C', '#2D707E', '#B08D3C', '#7A6C2E',
  '#3B6E8F', '#E07A5F', '#B7791F', '#D4A24C', '#4A7856',
  '#6B4C9A', '#C85E3A', '#2E7D32', '#1565C0', '#6D4C41'
];

function accentForCode(code) {
  const idx = ((code.charCodeAt(0) * 31) + (code.charCodeAt(1) || 0)) % ACCENT_COLORS.length;
  return ACCENT_COLORS[idx];
}

let countriesCache = null;
const COUNTRIES_RAW_PATH = path.join(__dirname, 'data/countries-raw.json');

function mapRestCountry(c) {
  const curated = destinations.find((d) => d.code === c.cca2);
  const currencyEntry = Object.entries(c.currencies || {})[0];
  return {
    code: c.cca2,
    name: c.name?.common || c.cca2,
    flag: c.flags?.emoji || c.flag || '',
    continent: c.continents?.[0] || c.region || 'Unknown',
    lat: c.latlng?.[0] || 0,
    lng: c.latlng?.[1] || 0,
    capital: c.capital?.[0] || '',
    currency: currencyEntry ? `${currencyEntry[1].name} (${currencyEntry[1].symbol || ''})` : '',
    language: Object.values(c.languages || {})[0] || '',
    accent: curated?.accent || accentForCode(c.cca2),
    // Curated extras — only for the original 10 destinations
    tagline: curated?.tagline || null,
    interests: curated?.interests || [],
    cheapestFlight: curated?.cheapestFlight || null,
    image: curated?.image || null
  };
}

async function getCountriesData() {
  if (countriesCache) return countriesCache;

  // 1. Local file (generated by scripts/fetch-countries.js)
  try {
    const raw = JSON.parse(fs.readFileSync(COUNTRIES_RAW_PATH, 'utf8'));
    if (Array.isArray(raw) && raw.length > 50) {
      countriesCache = raw.map(mapRestCountry).filter((c) => c.lat !== 0 || c.lng !== 0);
      console.log(`Loaded ${countriesCache.length} countries from local file`);
      return countriesCache;
    }
  } catch { /* file not yet generated */ }

  // 2. REST Countries API (save locally on success)
  try {
    const res = await fetch(
      'https://restcountries.com/v3.1/all?fields=name,cca2,flags,latlng,continents,capital,currencies,languages'
    );
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (!Array.isArray(data)) throw new Error('Unexpected response format');
    try { fs.writeFileSync(COUNTRIES_RAW_PATH, JSON.stringify(data)); } catch { /* ignore write errors */ }
    countriesCache = data.map(mapRestCountry).filter((c) => c.lat !== 0 || c.lng !== 0);
    console.log(`Loaded ${countriesCache.length} countries from REST Countries API`);
  } catch (err) {
    console.warn('REST Countries API unavailable, using curated 10:', err.message);
    countriesCache = destinations.map((d) => ({
      code: d.code, name: d.name, flag: d.flag, continent: d.continent,
      lat: d.lat, lng: d.lng, capital: d.facts.capital, currency: d.facts.currency,
      language: d.facts.language, accent: d.accent, tagline: d.tagline,
      interests: d.interests, cheapestFlight: d.cheapestFlight, image: d.image
    }));
  }
  return countriesCache;
}

// Preload at startup
getCountriesData();

// ════════════════════════════════════════════════════════════════════════════
//  COUNTRY ENDPOINTS
// ════════════════════════════════════════════════════════════════════════════

// All countries — used by the discover map
app.get('/api/countries', async (req, res) => {
  const list = await getCountriesData();
  const { continent } = req.query;
  const filtered = continent ? list.filter((c) => c.continent === continent) : list;
  res.json(filtered);
});

// Single country detail — used by the country page
app.get('/api/countries/:code', async (req, res) => {
  const code = req.params.code.toUpperCase();
  const list = await getCountriesData();
  const country = list.find((c) => c.code === code);
  if (!country) return res.status(404).json({ error: 'Country not found' });

  // Attach curated cultural content if available
  const curated = destinations.find((d) => d.code === code);
  res.json({
    ...country,
    intro: curated?.intro || null,
    didYouKnow: curated?.didYouKnow || null,
    highlights: curated?.highlights || null,
    cheapestFlight: curated?.cheapestFlight ?? country.cheapestFlight ?? null,
    comparison: curated?.comparison || null,
    facts: curated?.facts || {
      capital: country.capital,
      language: country.language,
      currency: country.currency,
      bestTime: '—'
    }
  });
});

// Cities for a country — sorted: large airports first, then alphabetically by city name
app.get('/api/countries/:code/cities', (req, res) => {
  const code = req.params.code.toUpperCase();
  const cities = airports
    .filter((a) => a.country === code)
    .sort((a, b) => {
      if (a.type !== b.type) return a.type === 'large_airport' ? -1 : 1;
      return a.city.localeCompare(b.city);
    });
  res.json(cities);
});

// ════════════════════════════════════════════════════════════════════════════
//  CITY ENDPOINTS
// ════════════════════════════════════════════════════════════════════════════

// City detail + AI-generated cultural content
app.get('/api/cities/:iata', async (req, res) => {
  const iata = req.params.iata.toUpperCase();
  const airport = airports.find((a) => a.iata === iata);
  if (!airport) return res.status(404).json({ error: 'City not found' });

  const countries = await getCountriesData();
  const country = countries.find((c) => c.code === airport.country);
  const countryName = country?.name || airport.country;

  const culture = await getCityCulture(iata, airport.city, countryName);

  res.json({ ...airport, countryName, culture });
});

// Flights to a city — real Amadeus when credentials present, mock fallback otherwise
app.get('/api/cities/:iata/flights', async (req, res) => {
  const iata = req.params.iata.toUpperCase();
  const airport = airports.find((a) => a.iata === iata);
  if (!airport) return res.status(404).json({ error: 'City not found' });

  const defaultDate = new Date(Date.now() + 30 * 86_400_000).toISOString().slice(0, 10);
  const departureDate = req.query.departureDate || defaultDate;
  const adults = parseInt(req.query.adults) || 1;
  const origin = req.query.origin || 'IST';

  const base = { iata, city: airport.city, from: origin, departureDate };

  // Reuse the curated mock for this IATA if it matches one of the 10 destinations
  const curated = destinations.find((d) => d.iata === iata);

  // Priority: Duffel (real-time) → Travelpayouts (cached) → mock
  const duffel = await fetchDuffelFlights(origin, iata, departureDate, adults);
  if (duffel) return res.json({ ...base, ...duffel });

  const tp = await fetchLiveFlights(origin, iata, departureDate);
  if (tp) return res.json({ ...base, ...tp });

  if (amadeus) {
    const cacheKey = `flights:${origin}:${iata}:${departureDate}:${adults}`;
    const cached = getCached(cacheKey);
    if (cached) return res.json({ ...base, source: 'live-cached', flights: cached });
    try {
      const response = await amadeus.shopping.flightOffersSearch.get({
        originLocationCode: origin, destinationLocationCode: iata,
        departureDate, adults: String(adults), max: '10', currencyCode: 'USD'
      });
      const carriers = response.result?.dictionaries?.carriers ?? {};
      const flights = response.data.map((offer) => mapOffer(offer, carriers));
      setCache(cacheKey, flights);
      return res.json({ ...base, source: 'live', flights });
    } catch (err) {
      console.error('Amadeus flight error:', err.description ?? err.message);
    }
  }

  const mockFlights = curated
    ? buildFlights(curated)
    : buildGenericFlights(iata, airport.city, origin);
  res.json({ ...base, source: 'mock', flights: mockFlights });
});

// Hotels in a city — Travelpayouts/Hotellook → Amadeus → mock
app.get('/api/cities/:iata/hotels', async (req, res) => {
  const iata = req.params.iata.toUpperCase();
  const airport = airports.find((a) => a.iata === iata);
  if (!airport) return res.status(404).json({ error: 'City not found' });

  const defaultCheckIn  = new Date(Date.now() + 30 * 86_400_000).toISOString().slice(0, 10);
  const defaultCheckOut = new Date(Date.now() + 33 * 86_400_000).toISOString().slice(0, 10);
  const checkIn  = req.query.checkIn  || defaultCheckIn;
  const checkOut = req.query.checkOut || defaultCheckOut;
  const adults   = parseInt(req.query.adults) || 1;

  const base = { iata, city: airport.city, checkIn, checkOut, adults };
  const curated = destinations.find((d) => d.iata === iata);

  // Priority: RapidAPI Booking.com → Travelpayouts → mock
  const rapidHotels = await fetchLiveHotelsRapidAPI(airport.city, checkIn, checkOut, adults);
  if (rapidHotels) return res.json({ ...base, ...rapidHotels });

  const tp = await fetchLiveHotelsTP(airport.city, checkIn, checkOut, adults);
  if (tp) return res.json({ ...base, ...tp });

  // Amadeus fallback
  if (amadeus) {
    try {
      const dest = curated || { code: airport.country, iata };
      const hotels = await fetchLiveHotels(dest, checkIn, checkOut, adults);
      if (hotels.length) return res.json({ ...base, source: 'live', hotels });
    } catch (err) {
      console.error('Amadeus hotel error:', err.description ?? err.message);
    }
  }

  const mockHotels = curated ? buildHotels(curated) : buildGenericHotels(iata, airport.city);
  res.json({ ...base, source: 'mock', hotels: mockHotels });
});

// Car rentals for a city — mock data (no free global car API exists)
app.get('/api/cities/:iata/cars', (req, res) => {
  const iata = req.params.iata.toUpperCase();
  const airport = airports.find((a) => a.iata === iata);
  if (!airport) return res.status(404).json({ error: 'City not found' });

  const curated = destinations.find((d) => d.iata === iata);
  const cars = curated ? buildCars(curated) : buildGenericCars(iata, airport.city);
  res.json({
    iata, city: airport.city,
    pickupDate: req.query.pickupDate || null,
    dropoffDate: req.query.dropoffDate || null,
    source: 'mock',
    cars
  });
});

// ════════════════════════════════════════════════════════════════════════════
//  GENERIC MOCK DATA BUILDERS (for non-curated cities)
// ════════════════════════════════════════════════════════════════════════════

const AIRLINES = ['Turkish Airlines', 'Pegasus', 'Lufthansa', 'Emirates', 'Qatar Airways'];
const STOPS = ['Direct', 'Direct', '1 Stop', 'Direct'];
const DEP_TIMES = ['09:40', '11:15', '14:50', '08:20'];
const ARR_TIMES = ['13:00', '16:20', '20:35', '12:35'];
const DURATIONS = ['3h 20m', '5h 05m', '6h 45m', '4h 15m'];

function buildGenericFlights(iata, city, origin) {
  const base = 400 + (iata.charCodeAt(0) + iata.charCodeAt(1) + iata.charCodeAt(2)) % 600;
  return DEP_TIMES.map((dep, i) => ({
    id: `${iata}-${i}`,
    airline: AIRLINES[i % AIRLINES.length],
    from: origin,
    to: iata,
    depart: dep,
    arrive: ARR_TIMES[i],
    duration: DURATIONS[i],
    stops: STOPS[i],
    price: base + i * 20 - (STOPS[i].includes('Stop') ? 40 : 0),
    deepLink: `https://www.skyscanner.net/transport/flights/${origin.toLowerCase()}/${iata.toLowerCase()}/`
  })).sort((a, b) => a.price - b.price);
}

const HOTEL_CHAINS = ['Marriott', 'Hilton', 'Hyatt', 'Radisson', 'Accor'];
const HOTEL_TYPES  = ['City Hotel', 'Resort', 'Boutique Hotel', 'Luxury Hotel', 'Budget Hotel'];

function buildGenericHotels(iata, city) {
  const base = 60 + (iata.charCodeAt(0) + iata.charCodeAt(2)) % 80;
  return HOTEL_CHAINS.map((chain, i) => ({
    id: `${iata}-hotel-${i}`,
    name: `${chain} ${city}`,
    chain,
    type: HOTEL_TYPES[i],
    stars: [5, 4, 4, 3, 3][i],
    rating: parseFloat((4.5 - i * 0.1).toFixed(1)),
    reviews: 200 + i * 150,
    pricePerNight: base + i * 15,
    currency: 'USD',
    amenities: ['WiFi', ...(i < 3 ? ['Pool'] : []), 'Restaurant'],
    address: `${city} City Centre`,
    deepLink: `https://www.booking.com/searchresults.html?ss=${encodeURIComponent(city)}`
  }));
}

const CAR_AGENCIES  = ['Hertz', 'Avis', 'Europcar', 'Sixt', 'Budget'];
const CAR_MODELS    = ['Toyota Yaris or similar', 'VW Golf or similar', 'Toyota RAV4 or similar', 'Mercedes C-Class or similar', 'Ford Galaxy or similar'];
const CAR_CATS      = ['Economy', 'Compact', 'SUV', 'Premium', 'Minivan'];

function buildGenericCars(iata, city) {
  const base = 25 + (iata.charCodeAt(1)) % 20;
  return CAR_AGENCIES.map((agency, i) => ({
    id: `${iata}-car-${i}`,
    agency,
    category: CAR_CATS[i],
    model: CAR_MODELS[i],
    transmission: i === 0 ? 'Manual' : 'Automatic',
    seats: [4, 5, 5, 5, 7][i],
    pricePerDay: base + i * 8,
    currency: 'USD',
    features: ['AC', ...(i > 1 ? ['GPS'] : [])],
    pickupLocation: `${iata} Airport`,
    deepLink: `https://www.rentalcars.com/en/airport/${iata.toLowerCase()}/`
  }));
}

// ════════════════════════════════════════════════════════════════════════════
//  AUTH ENDPOINTS
// ════════════════════════════════════════════════════════════════════════════

app.post('/api/auth/register', (req, res) => {
  const { name, email, password } = req.body || {};
  if (!name || !email || !password) return res.status(400).json({ error: 'Missing fields' });
  if (users.has(email)) return res.status(409).json({ error: 'Email already registered' });
  const user = { id: `u-${Date.now()}`, name, email, password, homeAirport: 'Istanbul — IST', currency: 'USD ($)', language: 'English' };
  users.set(email, user);
  savedByUser.set(user.id, new Set());
  const token = jwt.sign({ sub: user.id }, JWT_SECRET, { expiresIn: '7d' });
  res.json({ token, user: publicUser(user) });
});

app.post('/api/auth/login', (req, res) => {
  const { email, password } = req.body || {};
  const user = users.get(email);
  if (!user || user.password !== password) return res.status(401).json({ error: 'Invalid credentials' });
  const token = jwt.sign({ sub: user.id }, JWT_SECRET, { expiresIn: '7d' });
  res.json({ token, user: publicUser(user) });
});

app.get('/api/auth/me', auth, (req, res) => {
  const user = [...users.values()].find((u) => u.id === req.userId);
  if (!user) return res.status(404).json({ error: 'Not found' });
  res.json(publicUser(user));
});

app.put('/api/auth/me', auth, (req, res) => {
  const user = [...users.values()].find((u) => u.id === req.userId);
  if (!user) return res.status(404).json({ error: 'Not found' });
  const { name, homeAirport, currency, language } = req.body || {};
  if (name) user.name = name;
  if (homeAirport) user.homeAirport = homeAirport;
  if (currency) user.currency = currency;
  if (language) user.language = language;
  res.json(publicUser(user));
});

// ════════════════════════════════════════════════════════════════════════════
//  SAVED DESTINATIONS
// ════════════════════════════════════════════════════════════════════════════

app.get('/api/saved', auth, async (req, res) => {
  const codes = savedByUser.get(req.userId) || new Set();
  const list = await getCountriesData();
  const saved = list.filter((c) => codes.has(c.code));
  res.json(saved);
});

app.post('/api/saved/:code', auth, async (req, res) => {
  const code = req.params.code.toUpperCase();
  const list = await getCountriesData();
  if (!list.some((c) => c.code === code)) return res.status(404).json({ error: 'Country not found' });
  if (!savedByUser.has(req.userId)) savedByUser.set(req.userId, new Set());
  savedByUser.get(req.userId).add(code);
  res.json({ saved: [...savedByUser.get(req.userId)] });
});

app.delete('/api/saved/:code', auth, (req, res) => {
  const set = savedByUser.get(req.userId);
  if (set) set.delete(req.params.code.toUpperCase());
  res.json({ saved: set ? [...set] : [] });
});

// ════════════════════════════════════════════════════════════════════════════
//  SAVED TRIPS
// ════════════════════════════════════════════════════════════════════════════

app.get('/api/trips', auth, (req, res) => {
  res.json(tripsByUser.get(req.userId) || []);
});

app.post('/api/trips', auth, (req, res) => {
  const trip = { id: `t-${Date.now()}`, savedAt: new Date().toISOString(), ...req.body };
  if (!tripsByUser.has(req.userId)) tripsByUser.set(req.userId, []);
  tripsByUser.get(req.userId).unshift(trip);
  res.status(201).json(trip);
});

app.delete('/api/trips/:id', auth, (req, res) => {
  const list = tripsByUser.get(req.userId) || [];
  tripsByUser.set(req.userId, list.filter((t) => t.id !== req.params.id));
  res.json({ ok: true });
});

app.get('/api/health', (req, res) => res.json({ ok: true }));

app.listen(PORT, () => console.log(`GeoFlow backend running on http://localhost:${PORT}`));
